#!/bin/bash
# Video Knowledge Pipeline - P6 Project
# Bilibili video -> audio -> transcript -> summary -> Obsidian
# Usage: ./run_pipeline.sh <bilibili_url>

set -e

VIDEO_URL="${1:?Usage: $0 <bilibili_url>}"
TIMESTAMP=$(date +%Y%m%d-%H%M)
WORKDIR="/tmp/video-pipeline-${TIMESTAMP}"
VAULT_PATH="${OBSIDIAN_VAULT:-$HOME/Documents/obsidian-vault}"
SUMMARY_DIR="${VAULT_PATH}/video-summaries"

mkdir -p "$WORKDIR" "$SUMMARY_DIR"

echo "=== Video Knowledge Pipeline ==="
echo "URL: $VIDEO_URL"
echo "Workdir: $WORKDIR"
echo ""

# Step 1: Download audio
echo "[1/5] Downloading audio..."
if command -v yt-dlp &>/dev/null; then
    yt-dlp -x --audio-format mp3 -o "${WORKDIR}/audio.%(ext)s" "$VIDEO_URL" || {
        echo "WARNING: yt-dlp download failed."
    }
else
    echo "SKIP: yt-dlp not installed. Run: brew install yt-dlp"
fi

# Step 2: Transcribe with Whisper
echo "[2/5] Transcribing audio..."
if [ -f "${WORKDIR}/audio.mp3" ]; then
    if command -v whisper &>/dev/null; then
        whisper "${WORKDIR}/audio.mp3" --model small --output_dir "$WORKDIR" --output_format txt || true
    else
        echo "SKIP: whisper not installed. Run: pip install openai-whisper"
    fi
else
    echo "SKIP: No audio file to transcribe"
fi

# Step 3: Extract transcript
echo "[3/5] Extracting transcript..."
TRANSCRIPT=""
if [ -f "${WORKDIR}/audio.txt" ]; then
    TRANSCRIPT=$(head -c 5000 "${WORKDIR}/audio.txt")
elif [ -f "${WORKDIR}/audio.srt" ]; then
    TRANSCRIPT=$(grep -v '^[0-9]' "${WORKDIR}/audio.srt" | grep -v '^$' | grep -v '-->' | head -c 5000)
fi

# Step 4: Generate summary
echo "[4/5] Generating summary..."
SUMMARY_FILE="${SUMMARY_DIR}/${TIMESTAMP}-video-summary.md"

cat > "$SUMMARY_FILE" << EOF
# Video Summary - ${TIMESTAMP}

- **Source**: ${VIDEO_URL}
- **Processed**: $(date "+%Y-%m-%d %H:%M")

## Key Points

[To be filled by LLM after transcription]

## Transcript (first 5000 chars)

${TRANSCRIPT}

## Action Items

- [ ] Review and fill in key points
- [ ] Extract concepts to Obsidian vault
- [ ] Update video index

---
*Generated by video-knowledge-pipeline (P6)*
EOF

echo "Summary saved: $SUMMARY_FILE"

# Step 5: Update index
echo "[5/5] Updating index..."
INDEX_FILE="${SUMMARY_DIR}/README.md"
if [ ! -f "$INDEX_FILE" ]; then
    echo "# Video Summaries Index" > "$INDEX_FILE"
    echo "" >> "$INDEX_FILE"
fi
echo "- [${TIMESTAMP}](${TIMESTAMP}-video-summary.md) - ${VIDEO_URL}" >> "$INDEX_FILE"

echo ""
echo "=== Pipeline Complete ==="
echo "Summary: $SUMMARY_FILE"
echo "Cleanup with: rm -rf $WORKDIR"
